# Collector specific configuration
json_url: "https://hub.worldpop.org/rest/data/"
spreadsheet_url: "https://docs.google.com/spreadsheets/d/1TxeudQmWgOQcAQ1N2e94NzZ3l6T6n0Dq2-X48gkUBIw/edit?gid=1950485148#gid=1950485148"
