# Collector specific configuration
json_url: "https://www.worldpop.org/rest/data/"
country_indicators:
  pop: "wpgp"
  births: "bic"
  pregnancies: "individual_countries"
  age_structures: "aswpgp"
global_indicators:
  pop: "wpgp1km"
  age_structures: "aswpgponekm"
